# Generated by Django 3.1.6 on 2021-02-08 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signoff', '0002_auto_20210208_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signoff',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
